id: P004182
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG07597
  title: སྨན་གྱི་རྒྱུད་བཞིའི་བརྡ་དང་དོན་འགའ་ཞིག་བཀྲོལ་བ་རྣམ་རྒྱལ་ཨ་རུ་རའི་འཕྲེང་བའི་མཛེས་རྒྱན་
  author: ''
  volumes:
    0b01f51fe3a8452b95b3411241baadaf:
      image_group_id: I00KG07616
      title: ''
      volume_number: 1
      total_pages: 870
      base_file: v001.txt
    daaaa97394d24f39819bd275bd05b28b:
      image_group_id: I00KG07617
      title: ''
      volume_number: 2
      total_pages: 262
      base_file: v002.txt
