id: I25875CF3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:44:50+00:00'
last_modified: '2022-06-07T20:52:21.010225+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG07597
  title: སྨན་གྱི་རྒྱུད་བཞིའི་བརྡ་དང་དོན་འགའ་ཞིག་བཀྲོལ་བ་རྣམ་རྒྱལ་ཨ་རུ་རའི་འཕྲེང་བའི་མཛེས་རྒྱན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    39BD:
      image_group_id: I00KG07616
      title: ''
      total_pages: 870
      order: 1
      base_file: 39BD.txt
    3BAF:
      image_group_id: I00KG07617
      title: ''
      total_pages: 262
      order: 2
      base_file: 3BAF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
