id: I25875CF3
legacy_id: P004182
ocr_import_info:
  bdrc_scan_id: W00KG07597
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T14:42:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:03:54.403047+00:00'
last_modified: 2022-08-30 22:05:45.232684
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG07597
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG07597
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྨན་གྱི་རྒྱུད་བཞིའི་བརྡ་དང་དོན་འགའ་ཞིག་བཀྲོལ་བ་རྣམ་རྒྱལ་ཨ་རུ་རའི་འཕྲེང་བའི་མཛེས་རྒྱན།
  author: ལུང་རིགས་བསྟན་དར།
statistics:
  ocr_word_mean_confidence_index: 0.5271536986727733
  ocr_word_median_confidence_index: 0.49000000953674316
quality: null
bases:
  I00KG07616:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG07616
      total_pages: 870
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG07616.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5242021811725016
    legacy_id: v001
  I00KG07617:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG07617
      total_pages: 262
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00KG07617.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.538463945830739
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
